### ISSUE TITLE
Envelope

### ISSUE THREAD

**Issue by vr8hub** [davebytemfg/fritz-leiber_short-fiction#12]
I apologize, I saw this while I was looking at everything yesterday, but neglected to write it down in my notes, and so I forgot about it when I created the issues.

For the [envelope](https://github.com/davebytemfg/fritz-leiber_short-fiction/blob/a590ce9b211667991139b2d8eb3d8bb77372f2e0/src/epub/text/the-last-letter.xhtml#L56) in "The Last Letter":
1. Each line should be it's own paragraph. (I'm surprised `lint` didn't complain about the `<br/>`s used on something other than poem/song/verse.)
2. There are semantics for the sender, although it's usually in the letter itself, so it's covered in the [letter footer](https://standardebooks.org/manual/1.0.0/7-high-level-structural-patterns#7.7.3) section of the manual.
3. I don't think I've ever had an envelope without its contents; @acabal, when we have reference to an envelope by itself (see the link above), should it get semanticated as a letter, or just as a simple blockquote? The manual doesn't say anything about them.

**Comment by acabal** [comment]
I think we can remove the letter semantic, because it's an address and not a letter. Plain blockquote will be OK. sender semantics are not necessary because it's not in the context of a letter.

 `<br>` is appropriate if a single phrase is broken up into multiple lines for some stylistic reasons. This happens occasionally, for example in stylized dedications. I think in this case it's OK because addresses can typically be read as a single clause or line.

**Comment by davebytemfg** [comment]
Fixed in https://github.com/davebytemfg/fritz-leiber_short-fiction/tree/ddk-feedback-fixes

**Comment by davebytemfg** [comment]
@vr8hub - Vince! I think I've made all the changes from the issues. 

Small open questions to you (or alex) on #9, #7, #1 

I broke things into a couple of nested branches so I could review them myself, I'll take another review pass tomorrow.

After that, how do you want to check things? Should I merge everything up into the original repo, and then mark these issues closed? Or did you want to look at the branches independently?

Not sure of what kinds of process you'd like, let me know! 

Dave
