### ISSUE TITLE
Epigraphs

### ISSUE THREAD

**Issue by vr8hub** [davebytemfg/fritz-leiber_short-fiction#5]
Several of the stories have epigraphs, but you don't have the epigraph CSS in your CSS. See [here](https://standardebooks.org/manual/1.0.0/7-high-level-structural-patterns#7.4) in the manual.

This is also why your cite with an essay wasn't correct, so you should remove that from the se-lint-ignore file.

**Comment by davebytemfg** [comment]
added css in https://github.com/davebytemfg/fritz-leiber_short-fiction/tree/ddk-feedback-fixes

**Comment by davebytemfg** [comment]
To be clear, it reads like lint wants me to remove the <i> completely, because it's an essay, so I've removed the <i> and the epub:type completely? Leaving the essay name in quotes. Should I wrap it in a span or something instead? When I search a subset of the books I downloaded, they all seem to use <i> with the essay type.

See this change - https://github.com/davebytemfg/fritz-leiber_short-fiction/commit/813fb53de28b871b41be63074d364a08354e6a8d#diff-c84720466a13909cdb590c3cca33f580L344

**Comment by vr8hub** [comment]
No, the message doesn't say anything about the tag, it says it should not be _italicized_. There are two things at play here:
1. Italicizing vs quoting. Section 8.2.10 of the manual deals with this, and specifically mentions essays as something that should be quoted rather than italicized. (Part of "works that cannot stand alone".)
2. Semanticating. As a work that we have semantics for, it should be semanticated.

We put semantics on many things that we don't italicize, e.g. roman numerals. And just like with those, you would use a span for the essay as well.
