### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by vr8hub** [davebytemfg/fritz-leiber_short-fiction#9]
I don't think you need the tables in 64 Square Madhouse since there's only a single column. A regular `blockquote` with paragraphs will accomplish the same thing with a lot less complexity. You can use `<b>` on the names to get the formatting.

**Comment by davebytemfg** [comment]
Fixed in https://github.com/davebytemfg/fritz-leiber_short-fiction/tree/ddk-feedback-fixes

Once I merge this, take a look at the formatting again and confirm it's what you're expecting.

Here's a screenshot:

<img width="358" alt="Screen Shot 2020-08-10 at 7 31 45 PM" src="https://user-images.githubusercontent.com/68576981/89850922-26965e00-db40-11ea-8b56-de1fea3c10fa.png">

**Comment by vr8hub** [comment]
For the two or three instances of the blockquotes, you can use a header for the title, e.g. `<header>Last Round Pairings</header>`, and then target that in the CSS to center it and format it like you want. That way it matches the previous formatting.

**Comment by davebytemfg** [comment]
Fixed in https://github.com/davebytemfg/fritz-leiber_short-fiction/tree/ddk-feedback-fixes
